### ISSUE TITLE
ETH Safari: Making your first OD contribution

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/TBA#49]
update readme

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
Hello @Darlington02 I am Joseph Chimebuka I'm a full-stack software developer with 4+ years of experience in crafting innovative products. I've built a range of projects, showcasing my expertise in React, Next.js, and blockchain technologies. I also have written web3 articles for projects and even some on ERC 6551.  I'm also an active contributor onlydust. here's my account https://app.onlydust.com/u/josephchimebuka.

### How I plan on tackling this issue
I will reach out to the admin about specific information that should be update on the rR

**Comment by Darlington02** [comment]
Hey guys, it’s not a real issue. Needed it for a workshop today:(

I’d let you know when real issues pop up
