### ISSUE TITLE
ODHack: Upgrade cairo/starknet foundry version

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/TBA#57]
We just completed the v3 contracts for tokenbound. your task is to update the codebase in the v3 branch to use:

- Cairo v2.8.2
- Starknet Foundry v0.30.0

you'd need to also update the `.tool-versions` file and the github workflows.

**Comment by Oshioke-Salaki** [comment]
V

**Comment by martinvibes** [comment]
i would love to work on this issue @Darlington02

**Comment by ShantelPeters** [comment]
Can I be assigned to work on this ?
